In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv') 
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocessing the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
## Encode categorical variables

label_encoder_Gender = LabelEncoder()

data['Gender']= label_encoder_Gender.fit_transform(data['Gender']) 
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
# Onehot encode the 'Geography' column
from sklearn.preprocessing import OneHotEncoder
geo_oh_encoder = OneHotEncoder()
geo_encoder = geo_oh_encoder.fit_transform(data[['Geography']])
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [6]:
geo_oh_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_df = pd.DataFrame(geo_encoder.toarray(), columns=geo_oh_encoder.get_feature_names_out(['Geography']))
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
# combine the original data with the one-hot encoded geography data

data = pd.concat([data.drop('Geography', axis=1), geo_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
# Divide the dataset into independent and dependent features
x = data.drop('EstimatedSalary', axis=1)
y=data['EstimatedSalary'] 

# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [12]:
# Scale the features

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [13]:
# Save the encoders and scalar for later use
with open('label_encoder_Gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_Gender, file)
with open('geo_oh_encoder.pkl', 'wb') as file:
    pickle.dump(geo_oh_encoder, file)
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler,file)

## ANN Implementation with Regression Problem Statement

In [14]:
# ANN Implementation with Regression Problem Statement
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [16]:
## Build the ANN model
model= Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)), #HL1 connected with input layer
    Dense(32, activation='relu'), #HL2 connected with HL1
    Dense(1) # Regression output layer with 1 neuron and no activation function
]
)

c:\Users\MSI\python\ANN_Project\ml_env\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
# Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
import datetime

In [20]:
# Set up the tensorboard
from tensorflow.keras.callbacks import TensorBoard, EarlyStopping
log_dir="regressionlogs/fit/"+ datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callbacks= TensorBoard(log_dir=log_dir, histogram_freq=1)

In [21]:
# Setup early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [22]:
# Train the model
from calendar import EPOCH
from gc import callbacks

history= model.fit(
    x_train, y_train, validation_data=(x_test, y_test), epochs=100,
    callbacks=[tensorflow_callbacks, early_stopping ]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 100371.4375 - mae: 100371.4375 - val_loss: 98494.3047 - val_mae: 98494.3047
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99535.3672 - mae: 99535.3672 - val_loss: 96798.7969 - val_mae: 96798.7969
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 96576.9375 - mae: 96576.9375 - val_loss: 92452.4688 - val_mae: 92452.4688
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 90777.6875 - mae: 90777.6875 - val_loss: 85270.4375 - val_mae: 85270.4375
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 82441.4922 - mae: 82441.4922 - val_loss: 76172.3750 - val_mae: 76172.3750
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 72860.5234 - mae: 72860.5234 - val_loss: 66990.8047 - val_mae: 66990.8047
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 63949.9609 - mae: 63949.9609 - val_loss: 59394.3242 - val_mae: 59394.3242
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 57257.2188 - mae: 57257.2188 - val_loss: 54342.2070 - val_mae: 54342.2070
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 53187.6328 - mae: 53187.6328 - val_loss: 51780.1289 - val_mae: 51780.1289
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51205.3203 - mae: 51205.3203 - val_loss: 50890.2422 - val_mae: 50890.2422
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50439.5977 - mae: 50439.5977 - val_loss: 50637.5859 - val_mae: 50637.5859
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50171.6133 - mae: 50171.6133 - val_loss: 50574.7109 - val_mae: 50574.7109
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50071.7070 - mae: 50071.7070 - val_loss: 50533.9141 - val_mae: 50533.9141
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50011.0312 - mae: 50011.0312 - val_loss: 50512.7383 - val_mae: 50512.7383
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49963.7109 - mae: 49963.7109 - val_loss: 50489.9805 - val_mae: 50489.9805
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49923.9922 - mae: 49923.9922 - val_loss: 50469.6250 - val_mae: 50469.6250
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49886.1328 - mae: 49886.1328 - val_loss: 50449.6016 - val_mae: 50449.6016
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49855.9336 - mae: 49855.9336 - val_loss: 50424.2383 - val_mae: 50424.2383
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49826.7227 - mae: 49826.7227 - val_loss: 50412.0898 - val_mae: 50412.0898
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49802.9258 - mae: 49802.9258 - val_loss: 50409.1992 - val_mae: 50409.1992
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49779.5156 - mae: 49779.5156 - val_loss: 50393.9883 - val_mae: 50393.9883
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49754.6875 - mae: 49754.6875 - val_loss: 50394.0234 - val_mae: 50394.0234
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49736.9766 - mae: 49736.9766 - val_loss: 50384.6328 - val_mae: 50384.6328
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49720.5234 - mae: 49720.5234 - val_loss: 50378.2656 - val_mae: 50378.2656
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49703.9844 - mae: 49703.9844 - val_loss: 50379.5547 - val_mae: 50379.5547
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49685.7617 - mae: 49685.7617 - val_loss: 50363.9414 - val_mae: 50363.9414
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49674.0859 - mae: 49674.0859 - val_loss: 50372.0508 - val_mae: 50372.0508
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49656.9492 - mae: 49656.9492 - val_loss: 50366.7695 - val_mae: 50366.7695
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49644.2266 - mae: 49644.2266 - val_loss: 50362.3203 - val_mae: 50362.3203
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49631.9727 - mae: 49631.9727 - val_loss: 50351.7188 - val_mae: 50351.7188
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49620.0625 - mae: 49620.0625 - val_loss: 50356.0000 - val_mae: 50356.0000
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49608.4609 - mae: 49608.4609 - val_loss: 50356.5156 - val_mae: 50356.5156
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49596.0000 - mae: 49596.0000 - val_loss: 50355.9258 - val_mae: 50355.9258
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49582.9258 - mae: 49582.9258 - val_loss: 50348.9492 - val_mae: 50348.9492
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49574.9766 - mae: 49574.9766 - val_loss: 50351.6289 - val_mae: 50351.6289
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49566.8242 - mae: 49566.8242 - val_loss: 50342.8047 - val_mae: 50342.8047
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49554.9492 - mae: 49554.9492 - val_loss: 50338.4102 - val_mae: 50338.4102
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49547.1016 - mae: 49547.1016 - val_loss: 50335.0195 - val_mae: 50335.0195
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49535.2383 - mae: 49535.2383 - val_loss: 50338.9922 - val_mae: 50338.9922
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49527.3047 - mae: 49527.3047 - val_loss: 50335.1641 - val_mae: 50335.1641
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 49524.5039 - mae: 49524.5039 - val_loss: 50332.4688 - val_mae: 50332.4688
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49518.8398 - mae: 49518.8398 - val_loss: 50335.4766 - val_mae: 50335.4766
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49506.4492 - mae: 49506.4492 - val_loss: 50336.1523 - val_mae: 50336.1523
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49499.6016 - mae: 49499.6016 - val_loss: 50331.2539 - val_mae: 50331.2539
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49489.7891 - mae: 49489.7891 - val_loss: 50346.6602 - val_mae: 50346.6602
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49480.8164 - mae: 49480.8164 - val_loss: 50339.8555 - val_mae: 50339.8555
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49476.0742 - mae: 49476.0742 - val_loss: 50347.8594 - val_mae: 50347.8594
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49468.2266 - mae: 49468.2266 - val_loss: 50341.9375 - val_mae: 50341.9375
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49463.0859 - mae: 49463.0859 - val_loss: 50343.6250 - val_mae: 50343.6250
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49455.7891 - mae: 49455.7891 - val_loss: 50347.1094 - val_mae: 50347.1094
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49452.7852 - mae: 49452.7852 - val_loss: 50349.4219 - val_mae: 50349.4219
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49445.0469 - mae: 49445.0469 - val_loss: 50348.4766 - val_mae: 50348.4766
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49438.8984 - mae: 49438.8984 - val_loss: 50352.5977 - val_mae: 50352.5977
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49433.7266 - mae: 49433.7266 - val_loss: 50359.2266 - val_mae: 50359.2266

In [24]:
# Load TensorBoard Extension
%load_ext tensorboard
%tensorboard --logdir regressionlogs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 12532), started 0:01:38 ago. (Use '!kill 12532' to kill it.)

In [25]:
# Evaluate the model 
test_loss, test_mae= model.evaluate(x_test, y_test)
print(f'test_mae: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50331.2539 - mae: 50331.2539
test_mae: 50331.25390625

In [26]:
model.save('Regression_model.keras')